Repository palantir/resource-identifier, pull requests merged in 2021-07, with the labels that each got.

#140 Avoid allocation during validation
  .gitignore
  build.gradle
  changelog/@unreleased/pr-140.v2.yml
  src/jmh/java/com/palantir/ri/ResourceIdentifierBenchmark.java
  src/main/java/com/palantir/ri/ResourceIdentifier.java
  src/test/java/com/palantir/ri/ResourceIdentifierPropertyTest.java
  src/test/java/com/palantir/ri/ResourceIdentifierTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#143 Reduce string length method calls
  src/main/java/com/palantir/ri/ResourceIdentifier.java
Labels: autorelease, merge when ready, no changelog

#148 Require java 11 (up from java 8)
  build.gradle
  changelog/@unreleased/pr-148.v2.yml
Labels: merge when ready
